package main

import (
	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {
		for _, file := range plugin.Files {
			if !file.Generate {
				continue
			}

			g := plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+".pb.recaptcha.go", file.GoImportPath)
			g.P("// Code generated by recaptcha. DO NOT EDIT.")
			g.P()
			g.P("package ", file.GoPackageName)
			g.P()

			for _, service := range file.Services {
				g.P("// Service: ", service.GoName)
				g.P()
				GenerateService(g, service)
			}
		}

		return nil
	})
}
